create comment box
APDI-Team/AUS pull request #15
Opened 2023-01-16 06:58 UTC by sungjin122517

Used TextField widget and TextButton button to create comment box.
'Post' button is activated only when the user types something.

2023-01-18 13:54 UTC, syncdoth requested changes

2023-01-18 13:54 UTC, syncdoth commented on lib/views/comment_box.dart
> +              style: TextButton.styleFrom(foregroundColor: Colors.blue),
`foregroundColor` 가 안되네요. flutter version 이슈인진 모르겠는데...

2023-01-21 07:51 UTC, sungjin122517 commented on lib/views/comment_box.dart
> +              style: TextButton.styleFrom(foregroundColor: Colors.blue),
foregroundcolor를 primary로 변경했습니다

2023-01-21 10:44 UTC, syncdoth approved these changes

2023-01-21 10:45 UTC, merged