Save
APDI-Team/AUS pull request #29
Opened 2023-02-11 10:20 UTC by ChangmoPark

Save events -> 1. save count++ 2. firestore update to current user (savedEvents) 3. Change UI

Unsave events -> 1. save count-- 2. firestore update to current user(savedEvents) 3. Change UI

When Event is pressed -> viewCount++ (문제? 라고 해야하나: 한사람이 계속 나갔다 눌렀다 하면 viewCount 계속 올라감)

Extra: Register Button and Icon button size 수정

ToDo: Show savedEvents on Profile

2023-02-11 11:02 UTC, syncdoth commented on lib/views/profile_page.dart
> +                              savedPostRefs.add(data['savedPosts']);
savedEvents

2023-02-11 11:02 UTC, syncdoth commented on lib/views/components/event_ui.dart
> +            controller.event.firebaseDocRef
no need

2023-02-11 11:09 UTC, syncdoth requested changes

2023-02-11 11:09 UTC, syncdoth commented on lib/views/components/event_ui.dart
> +import 'package:cloud_firestore/cloud_firestore.dart';
delete

2023-02-11 11:09 UTC, syncdoth commented on lib/views/event_detail_page.dart
> +    FirebaseFirestore.instance.doc('user_info/$currentUserId').update({
collection('user_info').doc(currentUserId)

로 하는게 훨씬 깔끔함

2023-02-11 11:09 UTC, syncdoth commented on lib/views/event_detail_page.dart
> +
이런 whitespace 는 push 하기전에 신경써서 제거

2023-02-11 11:09 UTC, syncdoth commented on lib/views/event_detail_page.dart
> +                            stream: FirebaseFirestore.instance
stream 은 build 안에서 정의하지 말고 밖에서 해야함. line 29 밑에다가 

`Stream userStream = FirebaseFirestore.instance.collection('user_info').doc(currentUser.uid).snapshots();`

이런느낌으로 추가하고 여기엔 `stream: userStream` 이렇게 쓰는게 나음

2023-02-11 11:09 UTC, syncdoth commented on lib/views/event_detail_page.dart
> +  }
사실 이렇게 쓸거면 controller 가 존재하는 의미가 없음. saveEvent deleteEvent 둘다 EventController 의 함수로 작성해야함. 근데 귀찮으니까 걍 이렇게 하자

2023-02-14 16:40 UTC, syncdoth commented
merge commit, 그리고 이런저런 문제 해결 + 코드 더 좋게 짠 버전 이 브랜치에 푸시했으니 참고 바랍니다

2023-02-14 16:40 UTC, syncdoth approved these changes
이 브랜치의 마지막 commit 이 내가 문제점들 해결 및 코드 refactoring 해둔 거니까 읽어보시길 @ChangmoPark

2023-02-14 16:41 UTC, merged

2023-02-15 07:24 UTC, ChangmoPark commented
> 이 브랜치의 마지막 commit 이 내가 문제점들 해결 및 코드 refactoring 해둔 거니까 읽어보시길 @ChangmoPark

오케ㅔ 땡큐 형!