check url validity
APDI-Team/AUS pull request #39
Opened 2023-02-24 03:30 UTC by sungjin122517

2023-02-27 14:15 UTC, syncdoth requested changes

2023-02-27 14:15 UTC, syncdoth commented on lib/views/event_write_page.dart
> +                              Future.delayed(const Duration(milliseconds: 800),
Future.delayed 쓰지 말고,

`checkURL(eventRegistrationLink.text.trim()).then(....)` 에서 .... 안에 checkURL 이 끝난 뒤에 실행할 내용 넣으면 됩니다.

2023-02-28 01:56 UTC, sungjin122517 commented on lib/views/event_write_page.dart
> +                              Future.delayed(const Duration(milliseconds: 800),
변경 완료했습니다

2023-03-01 12:14 UTC, syncdoth approved these changes

2023-03-02 03:21 UTC, merged