UI
APDI-Team/AUS pull request #48
Opened 2023-03-31 19:27 UTC by ChangmoPark

UI update

2023-04-02 00:05 UTC, syncdoth requested changes

2023-04-02 00:05 UTC, syncdoth commented on lib/views/components/event_save_button.dart
> +      icon: saved
```
SvgPicture.asset(
saved ? 'assets/icons/save_true.svg' : 'assets/icons/save_false.svg',
width: 36,
height: 36,
)
```

2023-04-02 17:17 UTC, ChangmoPark commented on lib/views/components/event_save_button.dart
> +      icon: saved
오우,, 그런 방법이..

2023-04-03 10:03 UTC, syncdoth approved these changes

2023-04-03 10:04 UTC, merged