Analytics
APDI-Team/AUS pull request #54
Opened 2023-04-22 06:28 UTC by ChangmoPark

analytics

2023-04-22 14:21 UTC, syncdoth requested changes

2023-04-22 14:21 UTC, syncdoth commented on lib/views/home_page.dart
> +                "page number": _selectedIndex,
기왕이면 숫자 말고 string 으로?

`if (_selectedIndex == 0) page_name = 'events'`

이런식으로

2023-04-23 18:47 UTC, ChangmoPark commented on lib/views/home_page.dart
> +                "page number": _selectedIndex,
아ㅏ 저거 테스트 해보려고 한건데 오키오키 그렇게 할게!!

2023-04-24 14:45 UTC, syncdoth requested changes

2023-04-24 14:45 UTC, syncdoth commented on lib/views/home_page.dart
> +                "page number": _selectedIndex == 0
막간 코딩 강의:
`condition ? expression1 : expression2` 를 삼항 연산자라고 부름 (ternary operator). 이거는 기본적으로 one-liner 일때만 사용하는게 국룰임. 그래서 복잡한 로직에 삼항 연산자를 사용하면 readability 가 떨어지기 때문에 사용하지 않는게 좋음. 추가로 삼항 연산자를 nesting 하는 건 최대한 지양해야함.

그러니까 여기는 `if, else if` 사용해서 해결하는게 좋음.

2023-04-26 14:29 UTC, syncdoth approved these changes

2023-04-26 14:29 UTC, merged