Update UI 2
APDI-Team/AUS pull request #56
Opened 2023-04-24 13:56 UTC by sungjin122517

2023-04-24 14:47 UTC, syncdoth requested changes

2023-04-24 14:47 UTC, syncdoth commented on lib/views/event_write_page.dart
> +// import 'dart:html';
이거 import 빼주세요

2023-04-24 14:47 UTC, syncdoth commented on lib/views/components/custom_popup.dart
> +                    child: const Text("Yes, Sign Out")),
style 다 뺀 이유가 있나요?

2023-05-02 15:17 UTC, sungjin122517 commented on lib/views/components/custom_popup.dart
> +                    child: const Text("Yes, Sign Out")),
제가 custom한 rightButtonStyle()에 모두 포함되어있어서 뺐습니다

2023-05-02 15:18 UTC, sungjin122517 commented on lib/views/event_write_page.dart
> +// import 'dart:html';
완료

2023-05-03 19:44 UTC, syncdoth approved these changes
Lgtm

2023-05-04 04:05 UTC, merged