Create post
APDI-Team/AUS pull request #7
Opened 2022-12-21 17:26 UTC by ChangmoPark

Creating Post page
1. Basic structure of UI (horizontal list_view, textfields, Post button etc)
2. Pop up message when button is pushed
3. When pressed,  [Title, Content, current time, current user (ref)] is uploaded to the server (SUCCESSFUL)

2022-12-28 08:10 UTC, syncdoth requested changes

2022-12-28 08:10 UTC, syncdoth commented on lib/views/post_write_page.dart
> +          SizedBox(
앞으로 SizedBox 로 마진을 넣지 않으면 좋을듯. `Padding` 사용이 더 좋아보임

2023-01-07 12:19 UTC, ChangmoPark commented on lib/views/post_write_page.dart
> +          SizedBox(
방금 padding 으로 바꿔서 올렸는데 확인 부탁드려용

2023-01-07 12:55 UTC, ChangmoPark commented
방금 UI에서 이것저것 만져서 올렸습니다

2023-01-11 14:09 UTC, ChangmoPark commented
category 도 한개만 선택하여 String 으로 update 하게 했습니다

2023-01-18 13:38 UTC, apdi-dev approved these changes
자세하게는 안봤으나 작동하는 걸 보니 괜찮은 듯 보임. ios build version podfile 수정하는 코드가 들어가 있어서 다른 브랜치랑 합쳤을 때 컨플릭트 지옥일 것 같긴 하지만 ㅎ 언젠간 해야되는 것 같으니 approve 합니당

2023-01-18 13:39 UTC, syncdoth approved these changes

2023-01-18 13:40 UTC, merged